### ISSUE TITLE
Existing implementations

### ISSUE THREAD

**Issue by ioquatix** [piotrmurach/benchmark-malloc#1]
Maybe you already saw it, but https://github.com/socketry/async-rspec/blob/master/lib/async/rspec/memory/trace.rb might have something useful for you!

**Comment by piotrmurach** [comment]
Thanks for sharing. I created this gem to specifically power the https://github.com/piotrmurach/rspec-benchmark#15-allocation matcher. This is a set of RSpec matchers I've been working on for a couple of years now to make performance testing a bit easier.
